# bigip group vars
user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33626263363766393539626263353834396461653233643430373834353337653333373863623265
          6534373932646538323431626132633866343237643538620a343739343766653462653937313061
          66316236386432323863333263643836333861316333613137373939383265353736363861373932
          3663323839613739340a383266373966663161633763353262613638663638623865383530633239
          6361
password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64613237376339323931653762366261336464663735643034613561343437326361623939623661
          6166313638356231323938633636653565316538666239340a633662396433313039363534633666
          66643632313065326562376563656530653463643561623530373533386633333231383664653839
          3132643130326562360a616131393764613865373366653166343438303334326661383431616430
          6464
validate_certs: No
port: 0
vlanExtName: External
vlanIntName: Internal
interface11: 1.1
interface12: 1.2
rProtocols:
  - BFD
  - BGP
id: 0
vAddress: 8.8.8.8
vAddressName: VS-80
vAddrAvailability: yes
profiles: fastL4
netmask: 255.255.255.0
tagExt: 20
tagInt: 30
